spring:
  application:
    name: SpringJDBCDemo01

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode : always